### ISSUE TITLE
Tracking-related notifications on PC

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_editor#71] opened 2020-04-16 11:43 UTC
...should not be displayed

**Comment by xBambusekD** [comment] 2020-04-16 12:04
Which notifications are being displayed? AR stuff should be completely turned off when using PC version.

**Comment by ZdenekM** [comment] 2020-04-16 12:13
![Screenshot from 2020-04-16 13-42-16](https://user-images.githubusercontent.com/1199396/79454926-5dbe8d80-7fec-11ea-808e-1e600327a273.png)

Sorry - forget to attach screenshot.

**Comment by Kapim** [comment] 2020-04-17 06:18
Closing this as it is caused by tracking managed instance in standalone version, which is being addressed in #76

**Closed by Kapim** 2020-04-17 06:18 UTC
Labels: PC, enhancement
